project_id = "myeyoafugkrkwcnfedlu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[fetch.services]]
name = "notion"
url = "https://api.notion.com"