export function getPromptForSection(section: number, answers_json: string): string {
  const basePrompt = `Important: Always write your response in the second person, addressing the subject directly as "you". For example, use phrases like "Your philosophical DNA...", "You tend to...", "Your approach is..."

Here are your answers to the philosophical questions:

${answers_json}

Format your response as a FLAT JSON object with NO nesting. Use the exact field names specified in the template below.`;

  const templates = {
    1: `For Section 1 (Theology & Ontology), provide a JSON object with these exact fields:

{
  "archetype": "Domain Archetype",
  "archetype_definition": "Brief poetic subtitle capturing essence",
  "introduction": "Single paragraph capturing philosophical essence",
  "key_tension_1": "Key tension in thinking",
  "key_tension_2": "Key tension in thinking",
  "key_tension_3": "Key tension in thinking",
  "natural_strength_1": "Natural Strength",
  "natural_strength_2": "Natural Strength",
  "natural_strength_3": "Natural Strength",
  "growth_edges_1": "Growth Edge",
  "growth_edges_2": "Growth Edge",
  "growth_edges_3": "Growth Edge",
  "theology_introduction": "Approach to theology",
  "ontology_introduction": "Approach to ontology",
  "theology_kindred_spirit_1": "Thinker name",
  "theology_kindred_spirit_1_classic": "Work (Date)",
  "theology_kindred_spirit_1_rationale": "How their argument resonates",
  "theology_kindred_spirit_2": "Thinker name",
  "theology_kindred_spirit_2_classic": "Work (Date)",
  "theology_kindred_spirit_2_rationale": "How their argument resonates",
  "theology_kindred_spirit_3": "Thinker name",
  "theology_kindred_spirit_3_classic": "Work (Date)",
  "theology_kindred_spirit_3_rationale": "How their argument resonates",
  "theology_kindred_spirit_4": "Thinker name",
  "theology_kindred_spirit_4_classic": "Work (Date)",
  "theology_kindred_spirit_4_rationale": "How their argument resonates",
  "theology_kindred_spirit_5": "Thinker name",
  "theology_kindred_spirit_5_classic": "Work (Date)",
  "theology_kindred_spirit_5_rationale": "How their argument resonates",
  "theology_challenging_voice_1": "Thinker name",
  "theology_challenging_voice_1_classic": "Work (Date)",
  "theology_challenging_voice_1_rationale": "How their argument challenges",
  "theology_challenging_voice_2": "Thinker name",
  "theology_challenging_voice_2_classic": "Work (Date)",
  "theology_challenging_voice_2_rationale": "How their argument challenges",
  "theology_challenging_voice_3": "Thinker name",
  "theology_challenging_voice_3_classic": "Work (Date)",
  "theology_challenging_voice_3_rationale": "How their argument challenges",
  "theology_challenging_voice_4": "Thinker name",
  "theology_challenging_voice_4_classic": "Work (Date)",
  "theology_challenging_voice_4_rationale": "How their argument challenges",
  "theology_challenging_voice_5": "Thinker name",
  "theology_challenging_voice_5_classic": "Work (Date)",
  "theology_challenging_voice_5_rationale": "How their argument challenges",
  "ontology_kindred_spirit_1": "Thinker name",
  "ontology_kindred_spirit_1_classic": "Work (Date)",
  "ontology_kindred_spirit_1_rationale": "How their argument resonates",
  "ontology_kindred_spirit_2": "Thinker name",
  "ontology_kindred_spirit_2_classic": "Work (Date)",
  "ontology_kindred_spirit_2_rationale": "How their argument resonates",
  "ontology_kindred_spirit_3": "Thinker name",
  "ontology_kindred_spirit_3_classic": "Work (Date)",
  "ontology_kindred_spirit_3_rationale": "How their argument resonates",
  "ontology_kindred_spirit_4": "Thinker name",
  "ontology_kindred_spirit_4_classic": "Work (Date)",
  "ontology_kindred_spirit_4_rationale": "How their argument resonates",
  "ontology_kindred_spirit_5": "Thinker name",
  "ontology_kindred_spirit_5_classic": "Work (Date)",
  "ontology_kindred_spirit_5_rationale": "How their argument resonates",
  "ontology_challenging_voice_1": "Thinker name",
  "ontology_challenging_voice_1_classic": "Work (Date)",
  "ontology_challenging_voice_1_rationale": "How their argument challenges",
  "ontology_challenging_voice_2": "Thinker name",
  "ontology_challenging_voice_2_classic": "Work (Date)",
  "ontology_challenging_voice_2_rationale": "How their argument challenges",
  "ontology_challenging_voice_3": "Thinker name",
  "ontology_challenging_voice_3_classic": "Work (Date)",
  "ontology_challenging_voice_3_rationale": "How their argument challenges",
  "ontology_challenging_voice_4": "Thinker name",
  "ontology_challenging_voice_4_classic": "Work (Date)",
  "ontology_challenging_voice_4_rationale": "How their argument challenges",
  "ontology_challenging_voice_5": "Thinker name",
  "ontology_challenging_voice_5_classic": "Work (Date)",
  "ontology_challenging_voice_5_rationale": "How their argument challenges"
}`,

    2: `For Section 2 (Epistemology & Ethics), provide a JSON object with these exact fields:

{
  "epistemology_introduction": "Approach to epistemology",
  "ethics_introduction": "Approach to ethics",
  "epistemology_kindred_spirit_1": "Thinker name",
  "epistemology_kindred_spirit_1_classic": "Work (Date)",
  "epistemology_kindred_spirit_1_rationale": "How their argument resonates",
  "epistemology_kindred_spirit_2": "Thinker name",
  "epistemology_kindred_spirit_2_classic": "Work (Date)",
  "epistemology_kindred_spirit_2_rationale": "How their argument resonates",
  "epistemology_kindred_spirit_3": "Thinker name",
  "epistemology_kindred_spirit_3_classic": "Work (Date)",
  "epistemology_kindred_spirit_3_rationale": "How their argument resonates",
  "epistemology_kindred_spirit_4": "Thinker name",
  "epistemology_kindred_spirit_4_classic": "Work (Date)",
  "epistemology_kindred_spirit_4_rationale": "How their argument resonates",
  "epistemology_kindred_spirit_5": "Thinker name",
  "epistemology_kindred_spirit_5_classic": "Work (Date)",
  "epistemology_kindred_spirit_5_rationale": "How their argument resonates",
  "epistemology_challenging_voice_1": "Thinker name",
  "epistemology_challenging_voice_1_classic": "Work (Date)",
  "epistemology_challenging_voice_1_rationale": "How their argument challenges",
  "epistemology_challenging_voice_2": "Thinker name",
  "epistemology_challenging_voice_2_classic": "Work (Date)",
  "epistemology_challenging_voice_2_rationale": "How their argument challenges",
  "epistemology_challenging_voice_3": "Thinker name",
  "epistemology_challenging_voice_3_classic": "Work (Date)",
  "epistemology_challenging_voice_3_rationale": "How their argument challenges",
  "epistemology_challenging_voice_4": "Thinker name",
  "epistemology_challenging_voice_4_classic": "Work (Date)",
  "epistemology_challenging_voice_4_rationale": "How their argument challenges",
  "epistemology_challenging_voice_5": "Thinker name",
  "epistemology_challenging_voice_5_classic": "Work (Date)",
  "epistemology_challenging_voice_5_rationale": "How their argument challenges",
  "ethics_kindred_spirit_1": "Thinker name",
  "ethics_kindred_spirit_1_classic": "Work (Date)",
  "ethics_kindred_spirit_1_rationale": "How their argument resonates",
  "ethics_kindred_spirit_2": "Thinker name",
  "ethics_kindred_spirit_2_classic": "Work (Date)",
  "ethics_kindred_spirit_2_rationale": "How their argument resonates",
  "ethics_kindred_spirit_3": "Thinker name",
  "ethics_kindred_spirit_3_classic": "Work (Date)",
  "ethics_kindred_spirit_3_rationale": "How their argument resonates",
  "ethics_kindred_spirit_4": "Thinker name",
  "ethics_kindred_spirit_4_classic": "Work (Date)",
  "ethics_kindred_spirit_4_rationale": "How their argument resonates",
  "ethics_kindred_spirit_5": "Thinker name",
  "ethics_kindred_spirit_5_classic": "Work (Date)",
  "ethics_kindred_spirit_5_rationale": "How their argument resonates",
  "ethics_challenging_voice_1": "Thinker name",
  "ethics_challenging_voice_1_classic": "Work (Date)",
  "ethics_challenging_voice_1_rationale": "How their argument challenges",
  "ethics_challenging_voice_2": "Thinker name",
  "ethics_challenging_voice_2_classic": "Work (Date)",
  "ethics_challenging_voice_2_rationale": "How their argument challenges",
  "ethics_challenging_voice_3": "Thinker name",
  "ethics_challenging_voice_3_classic": "Work (Date)",
  "ethics_challenging_voice_3_rationale": "How their argument challenges",
  "ethics_challenging_voice_4": "Thinker name",
  "ethics_challenging_voice_4_classic": "Work (Date)",
  "ethics_challenging_voice_4_rationale": "How their argument challenges",
  "ethics_challenging_voice_5": "Thinker name",
  "ethics_challenging_voice_5_classic": "Work (Date)",
  "ethics_challenging_voice_5_rationale": "How their argument challenges"
}`,

    3: `For Section 3 (Politics & Aesthetics), provide a JSON object with these exact fields:

{
  "politics_introduction": "Approach to politics",
  "aesthetics_introduction": "Approach to aesthetics",
  "politics_kindred_spirit_1": "Thinker name",
  "politics_kindred_spirit_1_classic": "Work (Date)",
  "politics_kindred_spirit_1_rationale": "How their argument resonates",
  "politics_kindred_spirit_2": "Thinker name",
  "politics_kindred_spirit_2_classic": "Work (Date)",
  "politics_kindred_spirit_2_rationale": "How their argument resonates",
  "politics_kindred_spirit_3": "Thinker name",
  "politics_kindred_spirit_3_classic": "Work (Date)",
  "politics_kindred_spirit_3_rationale": "How their argument resonates",
  "politics_kindred_spirit_4": "Thinker name",
  "politics_kindred_spirit_4_classic": "Work (Date)",
  "politics_kindred_spirit_4_rationale": "How their argument resonates",
  "politics_kindred_spirit_5": "Thinker name",
  "politics_kindred_spirit_5_classic": "Work (Date)",
  "politics_kindred_spirit_5_rationale": "How their argument resonates",
  "politics_challenging_voice_1": "Thinker name",
  "politics_challenging_voice_1_classic": "Work (Date)",
  "politics_challenging_voice_1_rationale": "How their argument challenges",
  "politics_challenging_voice_2": "Thinker name",
  "politics_challenging_voice_2_classic": "Work (Date)",
  "politics_challenging_voice_2_rationale": "How their argument challenges",
  "politics_challenging_voice_3": "Thinker name",
  "politics_challenging_voice_3_classic": "Work (Date)",
  "politics_challenging_voice_3_rationale": "How their argument challenges",
  "politics_challenging_voice_4": "Thinker name",
  "politics_challenging_voice_4_classic": "Work (Date)",
  "politics_challenging_voice_4_rationale": "How their argument challenges",
  "politics_challenging_voice_5": "Thinker name",
  "politics_challenging_voice_5_classic": "Work (Date)",
  "politics_challenging_voice_5_rationale": "How their argument challenges",
  "aesthetics_kindred_spirit_1": "Thinker name",
  "aesthetics_kindred_spirit_1_classic": "Work (Date)",
  "aesthetics_kindred_spirit_1_rationale": "How their argument resonates",
  "aesthetics_kindred_spirit_2": "Thinker name",
  "aesthetics_kindred_spirit_2_classic": "Work (Date)",
  "aesthetics_kindred_spirit_2_rationale": "How their argument resonates",
  "aesthetics_kindred_spirit_3": "Thinker name",
  "aesthetics_kindred_spirit_3_classic": "Work (Date)",
  "aesthetics_kindred_spirit_3_rationale": "How their argument resonates",
  "aesthetics_kindred_spirit_4": "Thinker name",
  "aesthetics_kindred_spirit_4_classic": "Work (Date)",
  "aesthetics_kindred_spirit_4_rationale": "How their argument resonates",
  "aesthetics_kindred_spirit_5": "Thinker name",
  "aesthetics_kindred_spirit_5_classic": "Work (Date)",
  "aesthetics_kindred_spirit_5_rationale": "How their argument resonates",
  "aesthetics_challenging_voice_1": "Thinker name",
  "aesthetics_challenging_voice_1_classic": "Work (Date)",
  "aesthetics_challenging_voice_1_rationale": "How their argument challenges",
  "aesthetics_challenging_voice_2": "Thinker name",
  "aesthetics_challenging_voice_2_classic": "Work (Date)",
  "aesthetics_challenging_voice_2_rationale": "How their argument challenges",
  "aesthetics_challenging_voice_3": "Thinker name",
  "aesthetics_challenging_voice_3_classic": "Work (Date)",
  "aesthetics_challenging_voice_3_rationale": "How their argument challenges",
  "aesthetics_challenging_voice_4": "Thinker name",
  "aesthetics_challenging_voice_4_classic": "Work (Date)",
  "aesthetics_challenging_voice_4_rationale": "How their argument challenges",
  "aesthetics_challenging_voice_5": "Thinker name",
  "aesthetics_challenging_voice_5_classic": "Work (Date)",
  "aesthetics_challenging_voice_5_rationale": "How their argument challenges",
  "conclusion": "Brief synthesis of overall philosophical profile",
  "next_steps": "Practical suggestions for development"
}`;
  };

  return `${basePrompt}\n\n${templates[section as keyof typeof templates]}`;
}
