
export function getPromptForSection(section: number, answers_json: string): string {
  const template = {
    1: `Given these philosophical assessment answers: ${answers_json}

Please analyze the theology and ontology sections and return a JSON with these exact fields:
{
  "archetype": "Domain Archetype (format: [First Word] [Second Word], follow guidelines)",
  "archetype_definition": "Brief poetic subtitle capturing essence",
  "introduction": "Opening paragraph describing philosophical approach",
  "key_tension_1": "First key dialectic navigated",
  "key_tension_2": "Second key dialectic navigated",
  "key_tension_3": "Third key dialectic navigated",
  "natural_strength_1": "First inherent capacity",
  "natural_strength_2": "Second inherent capacity",
  "natural_strength_3": "Third inherent capacity",
  "growth_edges_1": "First growth area",
  "growth_edges_2": "Second growth area",
  "growth_edges_3": "Third growth area",
  "become_who_you_are": "Affirmation statement",
  "theology_introduction": "Theology approach summary",
  "ontology_introduction": "Ontology approach summary",
  "theology_kindred_spirit_1": "Name",
  "theology_kindred_spirit_1_classic": "Work (Date)",
  "theology_kindred_spirit_1_rationale": "Resonance explanation",
  "theology_kindred_spirit_2": "Name",
  "theology_kindred_spirit_2_classic": "Work (Date)",
  "theology_kindred_spirit_2_rationale": "Resonance explanation",
  "theology_kindred_spirit_3": "Name",
  "theology_kindred_spirit_3_classic": "Work (Date)",
  "theology_kindred_spirit_3_rationale": "Resonance explanation",
  "theology_kindred_spirit_4": "Name",
  "theology_kindred_spirit_4_classic": "Work (Date)",
  "theology_kindred_spirit_4_rationale": "Resonance explanation",
  "theology_kindred_spirit_5": "Name",
  "theology_kindred_spirit_5_classic": "Work (Date)",
  "theology_kindred_spirit_5_rationale": "Resonance explanation",
  "theology_challenging_voice_1": "Name",
  "theology_challenging_voice_1_classic": "Work (Date)",
  "theology_challenging_voice_1_rationale": "Challenge explanation",
  "theology_challenging_voice_2": "Name",
  "theology_challenging_voice_2_classic": "Work (Date)",
  "theology_challenging_voice_2_rationale": "Challenge explanation",
  "theology_challenging_voice_3": "Name",
  "theology_challenging_voice_3_classic": "Work (Date)",
  "theology_challenging_voice_3_rationale": "Challenge explanation",
  "theology_challenging_voice_4": "Name",
  "theology_challenging_voice_4_classic": "Work (Date)",
  "theology_challenging_voice_4_rationale": "Challenge explanation",
  "theology_challenging_voice_5": "Name",
  "theology_challenging_voice_5_classic": "Work (Date)",
  "theology_challenging_voice_5_rationale": "Challenge explanation",
  "ontology_kindred_spirit_1": "Name",
  "ontology_kindred_spirit_1_classic": "Work (Date)",
  "ontology_kindred_spirit_1_rationale": "Resonance explanation",
  "ontology_kindred_spirit_2": "Name",
  "ontology_kindred_spirit_2_classic": "Work (Date)", 
  "ontology_kindred_spirit_2_rationale": "Resonance explanation",
  "ontology_kindred_spirit_3": "Name",
  "ontology_kindred_spirit_3_classic": "Work (Date)",
  "ontology_kindred_spirit_3_rationale": "Resonance explanation",
  "ontology_kindred_spirit_4": "Name",
  "ontology_kindred_spirit_4_classic": "Work (Date)",
  "ontology_kindred_spirit_4_rationale": "Resonance explanation",
  "ontology_kindred_spirit_5": "Name",
  "ontology_kindred_spirit_5_classic": "Work (Date)",
  "ontology_kindred_spirit_5_rationale": "Resonance explanation"
}`,
    2: `Given these philosophical assessment answers: ${answers_json}

Please analyze the epistemology and ethics sections and return a JSON with these exact fields:
{
  "epistemology_introduction": "Epistemology approach summary",
  "ethics_introduction": "Ethics approach summary",
  "epistemology_kindred_spirit_1": "Name",
  "epistemology_kindred_spirit_1_classic": "Work (Date)",
  "epistemology_kindred_spirit_1_rationale": "Resonance explanation",
  "epistemology_kindred_spirit_2": "Name",
  "epistemology_kindred_spirit_2_classic": "Work (Date)",
  "epistemology_kindred_spirit_2_rationale": "Resonance explanation",
  "epistemology_kindred_spirit_3": "Name",
  "epistemology_kindred_spirit_3_classic": "Work (Date)",
  "epistemology_kindred_spirit_3_rationale": "Resonance explanation",
  "epistemology_kindred_spirit_4": "Name",
  "epistemology_kindred_spirit_4_classic": "Work (Date)",
  "epistemology_kindred_spirit_4_rationale": "Resonance explanation",
  "epistemology_kindred_spirit_5": "Name",
  "epistemology_kindred_spirit_5_classic": "Work (Date)",
  "epistemology_kindred_spirit_5_rationale": "Resonance explanation",
  "epistemology_challenging_voice_1": "Name",
  "epistemology_challenging_voice_1_classic": "Work (Date)",
  "epistemology_challenging_voice_1_rationale": "Challenge explanation",
  "epistemology_challenging_voice_2": "Name",
  "epistemology_challenging_voice_2_classic": "Work (Date)",
  "epistemology_challenging_voice_2_rationale": "Challenge explanation",
  "epistemology_challenging_voice_3": "Name",
  "epistemology_challenging_voice_3_classic": "Work (Date)",
  "epistemology_challenging_voice_3_rationale": "Challenge explanation",
  "epistemology_challenging_voice_4": "Name",
  "epistemology_challenging_voice_4_classic": "Work (Date)",
  "epistemology_challenging_voice_4_rationale": "Challenge explanation",
  "epistemology_challenging_voice_5": "Name",
  "epistemology_challenging_voice_5_classic": "Work (Date)",
  "epistemology_challenging_voice_5_rationale": "Challenge explanation",
  "ethics_kindred_spirit_1": "Name",
  "ethics_kindred_spirit_1_classic": "Work (Date)",
  "ethics_kindred_spirit_1_rationale": "Resonance explanation",
  "ethics_kindred_spirit_2": "Name",
  "ethics_kindred_spirit_2_classic": "Work (Date)",
  "ethics_kindred_spirit_2_rationale": "Resonance explanation",
  "ethics_kindred_spirit_3": "Name",
  "ethics_kindred_spirit_3_classic": "Work (Date)",
  "ethics_kindred_spirit_3_rationale": "Resonance explanation",
  "ethics_kindred_spirit_4": "Name",
  "ethics_kindred_spirit_4_classic": "Work (Date)",
  "ethics_kindred_spirit_4_rationale": "Resonance explanation",
  "ethics_kindred_spirit_5": "Name",
  "ethics_kindred_spirit_5_classic": "Work (Date)",
  "ethics_kindred_spirit_5_rationale": "Resonance explanation"
}`,
    3: `Given these philosophical assessment answers: ${answers_json}

Please analyze the politics and aesthetics sections and return a JSON with these exact fields:
{
  "politics_introduction": "Politics approach summary",
  "aesthetics_introduction": "Aesthetics approach summary",
  "politics_kindred_spirit_1": "Name",
  "politics_kindred_spirit_1_classic": "Work (Date)",
  "politics_kindred_spirit_1_rationale": "Resonance explanation",
  "politics_kindred_spirit_2": "Name",
  "politics_kindred_spirit_2_classic": "Work (Date)",
  "politics_kindred_spirit_2_rationale": "Resonance explanation",
  "politics_kindred_spirit_3": "Name",
  "politics_kindred_spirit_3_classic": "Work (Date)",
  "politics_kindred_spirit_3_rationale": "Resonance explanation",
  "politics_kindred_spirit_4": "Name",
  "politics_kindred_spirit_4_classic": "Work (Date)",
  "politics_kindred_spirit_4_rationale": "Resonance explanation",
  "politics_kindred_spirit_5": "Name",
  "politics_kindred_spirit_5_classic": "Work (Date)",
  "politics_kindred_spirit_5_rationale": "Resonance explanation",
  "politics_challenging_voice_1": "Name",
  "politics_challenging_voice_1_classic": "Work (Date)",
  "politics_challenging_voice_1_rationale": "Challenge explanation",
  "politics_challenging_voice_2": "Name",
  "politics_challenging_voice_2_classic": "Work (Date)",
  "politics_challenging_voice_2_rationale": "Challenge explanation",
  "politics_challenging_voice_3": "Name",
  "politics_challenging_voice_3_classic": "Work (Date)",
  "politics_challenging_voice_3_rationale": "Challenge explanation",
  "politics_challenging_voice_4": "Name",
  "politics_challenging_voice_4_classic": "Work (Date)",
  "politics_challenging_voice_4_rationale": "Challenge explanation",
  "politics_challenging_voice_5": "Name",
  "politics_challenging_voice_5_classic": "Work (Date)",
  "politics_challenging_voice_5_rationale": "Challenge explanation",
  "aesthetics_kindred_spirit_1": "Name",
  "aesthetics_kindred_spirit_1_classic": "Work (Date)",
  "aesthetics_kindred_spirit_1_rationale": "Resonance explanation",
  "aesthetics_kindred_spirit_2": "Name",
  "aesthetics_kindred_spirit_2_classic": "Work (Date)",
  "aesthetics_kindred_spirit_2_rationale": "Resonance explanation",
  "aesthetics_kindred_spirit_3": "Name",
  "aesthetics_kindred_spirit_3_classic": "Work (Date)",
  "aesthetics_kindred_spirit_3_rationale": "Resonance explanation",
  "aesthetics_kindred_spirit_4": "Name",
  "aesthetics_kindred_spirit_4_classic": "Work (Date)",
  "aesthetics_kindred_spirit_4_rationale": "Resonance explanation",
  "aesthetics_kindred_spirit_5": "Name",
  "aesthetics_kindred_spirit_5_classic": "Work (Date)",
  "aesthetics_kindred_spirit_5_rationale": "Resonance explanation"
}`;
  };

  return template[section as keyof typeof template] || '';
}
